version: '3.8'

services:
  web:
    build: .
    image: user/django-glmirror
    restart: unless-stopped
    volumes:
      - ./code:/code
      - db_data:/code/db
      - storage:/code/media
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db

  worker:
    image: user/django-glmirror
    restart: unless-stopped
    command: celery -A glmirror worker -l INFO -c 1 -E
    volumes:
      - ./code:/code
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - rabbitmq

  beat:
    image: user/django-glmirror
    restart: unless-stopped
    command: celery -A glmirror beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./code:/code
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    hostname: django-rabbit
    container_name: django-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672:15672"
    depends_on:
      - web
    
volumes:
  db_data:
  storage:
