# Generated by Django 4.1.5 on 2023-01-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='file',
            name='content',
        ),
    ]
