# Generated by Django 4.1.5 on 2023-01-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0002_remove_directory_parent_remove_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='kind',
            field=models.CharField(blank=True, choices=[('movie', 'movie'), ('image', 'image')], max_length=100, null=True),
        ),
    ]
