# Generated by Django 4.1.5 on 2023-01-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0003_file_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='filename',
        ),
    ]
