# Generated by Django 4.1.5 on 2023-01-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0006_rename_filename_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='kind',
        ),
    ]
