# Generated by Django 4.1.5 on 2023-01-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0009_search_search_unique search name'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_file_selected', to='filesystem.file'),
        ),
    ]
