# Generated by Django 4.1.5 on 2023-01-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0010_search_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_file_selected', to='filesystem.search'),
        ),
    ]
