# Generated by Django 4.1.5 on 2023-01-14 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0011_remove_search_file_file_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='search',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_file_selected', to='filesystem.search'),
        ),
    ]
