# Generated by Django 4.1.5 on 2023-01-14 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0035_delete_search'),
        ('filesystem', '0015_alter_search_file_alter_search_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_file_selected', to='filesystem.search'),
        ),
        migrations.AlterField(
            model_name='search',
            name='first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_first_selected', to='tmdb.movie'),
        ),
    ]
