# Generated by Django 4.1.5 on 2023-01-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0016_remove_search_file_file_search_alter_search_first'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='search',
            name='unique search name',
        ),
    ]
