# Generated by Django 4.1.5 on 2023-01-15 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0046_delete_search'),
        ('filesystem', '0019_rename_directory_moviesdirectory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('result', models.JSONField(blank=True, null=True)),
                ('last_search', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_file_selected', to='filesystem.videofile')),
                ('movie_selected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_movie_selected', to='tmdb.movie')),
            ],
        ),
        migrations.AddConstraint(
            model_name='search',
            constraint=models.UniqueConstraint(fields=('file',), name='unique search name'),
        ),
    ]
