# Generated by Django 4.1.5 on 2023-01-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0046_delete_search'),
        ('filesystem', '0020_search_search_unique search name'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='movies',
            field=models.ManyToManyField(related_name='search_movies', to='tmdb.movie'),
        ),
    ]
