# Generated by Django 4.1.5 on 2023-01-19 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tmdb', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FilePathField(allow_files=False, allow_folders=True, path='/mnt/media', recursive=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extension', models.CharField(blank=True, max_length=100, null=True)),
                ('realpath', models.TextField(blank=True, null=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='filesystem.moviesdirectory')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('result', models.JSONField(blank=True, null=True)),
                ('last_search', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_file_selected', to='filesystem.videofile')),
                ('movie_selected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_movie_selected', to='tmdb.movie')),
                ('movies', models.ManyToManyField(related_name='search_movies', to='tmdb.movie')),
            ],
        ),
        migrations.AddConstraint(
            model_name='search',
            constraint=models.UniqueConstraint(fields=('file',), name='unique search name'),
        ),
    ]
