# Generated by Django 4.1.5 on 2023-01-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0034_delete_movieassociation'),
        ('filesystem', '0007_remove_file_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='tmdb.movie'),
        ),
    ]
