# Generated by Django 4.1.5 on 2023-01-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0035_delete_search'),
        ('filesystem', '0008_file_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('result', models.JSONField(blank=True, null=True)),
                ('last_search', models.DateTimeField(auto_now=True)),
                ('first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_first_selected', to='tmdb.movie')),
            ],
        ),
        migrations.AddConstraint(
            model_name='search',
            constraint=models.UniqueConstraint(fields=('name',), name='unique search name'),
        ),
    ]
