# Generated by Django 4.1.5 on 2023-01-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0013_remove_file_search_search_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='search',
            new_name='file',
        ),
    ]
