# Generated by Django 4.1.5 on 2023-01-14 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0035_delete_search'),
        ('filesystem', '0014_rename_search_search_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_selected', to='filesystem.file'),
        ),
        migrations.AlterField(
            model_name='search',
            name='first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_selected', to='tmdb.movie'),
        ),
    ]
