# Generated by Django 4.1.5 on 2023-01-15 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0017_remove_search_unique search name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='file',
            name='search',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
