# Generated by Django 4.1.5 on 2023-01-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0037_movie_file'),
        ('filesystem', '0018_remove_file_movie_remove_file_search_delete_search'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directory',
            new_name='MoviesDirectory',
        ),
        migrations.RenameModel(
            old_name='File',
            new_name='VideoFile',
        ),
    ]
