# Generated by Django 4.1.5 on 2023-01-13 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='tmdb.movie'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ManyToManyField(blank=True, related_name='movie', to='tmdb.image'),
        ),
    ]
