# Generated by Django 4.1.5 on 2023-01-13 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0007_remove_movie_poster_movie_poster_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='poster_selected', to='tmdb.image'),
        ),
    ]
