# Generated by Django 4.1.5 on 2023-01-13 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0008_alter_movie_poster_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster_selected',
        ),
        migrations.AlterField(
            model_name='image',
            name='Movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='image', to='tmdb.movie'),
        ),
    ]
