# Generated by Django 4.1.5 on 2023-01-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0009_remove_movie_poster_selected_alter_image_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Movie',
        ),
    ]
