# Generated by Django 4.1.5 on 2023-01-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0013_rename_year_movie_tmdb_id_movie_original_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='original_title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
