# Generated by Django 4.1.5 on 2023-01-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0014_remove_movie_original_title_remove_movie_overview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='tmdb_id',
        ),
    ]
