# Generated by Django 4.1.5 on 2023-01-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0021_remove_setting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
