# Generated by Django 4.1.5 on 2023-01-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0033_search_unique search name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieAssociation',
        ),
    ]
