# Generated by Django 4.1.5 on 2023-01-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0018_remove_file_movie_remove_file_search_delete_search'),
        ('tmdb', '0036_search_image_unique image name_search_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file',
            field=models.ManyToManyField(blank=True, related_name='movie_file_selected', to='filesystem.file'),
        ),
    ]
