# Generated by Django 4.1.5 on 2023-01-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0042_remove_search_movies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_file',
        ),
    ]
