# Generated by Django 4.1.5 on 2023-01-13 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tmdb.movie')),
            ],
        ),
    ]
