# Generated by Django 4.1.5 on 2023-01-13 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0002_alter_image_movie_remove_movie_poster_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='tmdb.movie'),
        ),
    ]
