# Generated by Django 4.1.5 on 2023-01-13 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0010_remove_image_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='movie_images', to='tmdb.image'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_poster_selected', to='tmdb.image'),
        ),
    ]
