# Generated by Django 4.1.5 on 2023-01-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0003_file_kind'),
        ('tmdb', '0011_movie_image_movie_poster_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesystem.file')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdb.movie')),
            ],
        ),
    ]
