# Generated by Django 4.1.5 on 2023-01-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0018_remove_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster_selected',
            new_name='image',
        ),
    ]
