# Generated by Django 4.1.5 on 2023-01-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0020_settingoption_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='name',
        ),
    ]
