# Generated by Django 4.1.5 on 2023-01-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0022_alter_image_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
