# Generated by Django 4.1.5 on 2023-01-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0025_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='size',
        ),
    ]
