# Generated by Django 4.1.5 on 2023-01-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0026_remove_image_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
