# Generated by Django 4.1.5 on 2023-01-13 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0029_alter_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_first_selected', to='tmdb.movie'),
        ),
    ]
