# Generated by Django 4.1.5 on 2023-01-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0032_search_last_search'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='search',
            constraint=models.UniqueConstraint(fields=('name',), name='unique search name'),
        ),
    ]
