# Generated by Django 4.1.5 on 2023-01-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0034_delete_movieassociation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
