# Generated by Django 4.1.5 on 2023-01-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0037_movie_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='download_error',
            field=models.BooleanField(default=False),
        ),
    ]
