# Generated by Django 4.1.5 on 2023-01-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0038_movie_download_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='download_error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
