# Generated by Django 4.1.5 on 2023-01-15 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0040_remove_movie_download_error_movie_download_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='first',
        ),
        migrations.AddField(
            model_name='search',
            name='movie_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_movie_selected', to='tmdb.movie'),
        ),
        migrations.AddField(
            model_name='search',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='search_movies', to='tmdb.movie'),
        ),
    ]
