# Generated by Django 4.1.5 on 2023-01-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0041_remove_search_first_search_movie_selected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='movies',
        ),
    ]
