# Generated by Django 4.1.5 on 2023-01-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0043_rename_image_image_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='file',
        ),
    ]
