# Generated by Django 4.1.5 on 2023-01-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0044_remove_movie_file'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='search',
            constraint=models.UniqueConstraint(fields=('file',), name='unique search name'),
        ),
    ]
