# Generated by Django 4.1.5 on 2023-01-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0045_search_unique search name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
